[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "chess-scrappers"
version = "1.0.0"
requires-python = ">=3.12"
authors = [
  {name = "Andrzej Kulesza", email = "andykrk22@gmail.com"},
]
description = "Chess pgn scrappers for chessarbiter, chessmanager, chess-results, media idchess and brodcast: chessbase and lichess"
readme = "README.md"

dependencies = [
    "beautifulsoup4==4.15.0",
    "chess==1.11.2",
    "lxml==6.1.1",
    "packaging==26.3",
    "PyInputPlus==0.2.12",
    "requests==2.34.2",
    "selenium==4.47.0",
    "types-selenium==3.141.9",
    "typing_extensions==4.16.0",
    "undetected-chromedriver==3.5.5",
    "Unidecode==1.4.0",
    "zstandard==0.25.0",
]

[project.optional-dependencies]
dev = [
    "mypy==2.3.1",
    "mypy_extensions==1.1.0",
    "ruff==0.16.3"
]

[tool.setuptools]
py-modules = []

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = [
    ".git",
    ".github",
    ".venv",
    "__pycache__",
    "lichess_downloaded",
    "lichess_pgns",
    "twic_downloaded",
    "twic_pgns",
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # Pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
    "SIM",  # flake8-simplify\
    "RET",  # flake8-return
]
ignore = [
    "E501",  # line-too-long (handled by formatter)
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.mypy]
python_version = "3.12"
strict = true

check_untyped_defs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_any_generics = true

no_implicit_optional = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

ignore_missing_imports = true